.Informations générales
[format="csv"]
|======================
Rédacteur, K3rn€l P4n1k
Date, samedi 22 avril 2017
État, Rédigé
|======================

.License
Ce programme est un logiciel libre ; vous pouvez le redistribuer ou le modifier suivant les termes de la GNU General Public License telle que publiée par la Free Software Foundation ; soit la version 3 de la licence, soit (à votre gré) toute version ultérieure.

Ce programme est distribué dans l'espoir qu'il sera utile, mais SANS AUCUNE GARANTIE ; sans même la garantie tacite de QUALITÉ MARCHANDE ou d'ADÉQUATION à UN BUT PARTICULIER. Consultez la GNU General Public License pour plus de détails.

Vous devez avoir reçu une copie de la GNU General Public License en même temps que ce programme ; si ce n'est pas le cas, consultez <http://www.gnu.org/licenses>.


# Renversement de csv

.Objectif du document
Documente l'usage des scripts présent dans ce repository.

.Description générale
Les scripts présents ici ont pour but de permettre de renverser la disposition d'un fichier de données.

.Intention
Travailler avec les scripts de collatz.

## Dépendences

.Liste des dépendences
[format="csv", options="header"]
|====
Description, Dépendences, Mannuel
Format de fichier, awk, https://www.gnu.org/software/gawk/manual/gawk.html
|====

## Usage

.Signature
[source, bash]
----
reverse-csv <file.csv>
----

.Arguments
[format="csv"]
|====
file.csv, obligatoire, Fichier csv à formatter
|====

.Exemple
[source, bash]
----
reverse-csv 1,2,3,4
# Résultat
# 4,3,2,1
----

## Commentaires
Le script `reverse-ssv` s'utilise de la même mannière.
